// Automatically generated by astro-icon
// 54ec11731eabffba1433a4a27f21b839ce377ae2b0eb637aa25ecf6d93ef157b

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "heart-empty"
		| "heart-fill";
}